name: 🤖Add New Issue To Project


defaults:
  run:
    shell: pwsh


on:
  pull_request_target:
    types: opened
    branches: [main, preview, renovate/*]


jobs:
  add_new_issue_to_project:
    name: Add New Issue
    runs-on: ubuntu-latest
    steps:
      - name: Add PR To Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: "https://github.com/orgs/${{ vars.ORGANIZATION_NAME }}/projects/${{ vars.ORG_PROJECT_NUMBER }}"
          github-token: ${{ secrets.CICD_TOKEN }}
