name: ✅Build Status Check
run-name: ✅Build Status Check (${{ github.base_ref }} branch)


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: [main, preview]


jobs:
  build_main_project:
    name: Build ${{ vars.PROJECT_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Restore ${{ vars.PROJECT_NAME }} Dependencies
        run: dotnet restore "${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.csproj"

      - name: Build ${{ vars.PROJECT_NAME }}
        run: dotnet build "${{ github.workspace }}/${{ vars.PROJECT_NAME }}/${{ vars.PROJECT_NAME }}.csproj" -c Debug --no-restore


  build_perf_project:
    name: Build ${{ vars.PROJECT_NAME }}PerfTests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Restore ${{ vars.PROJECT_NAME }}PerfTests Dependencies
        run: dotnet restore "${{ github.workspace }}/Testing/${{ vars.PROJECT_NAME }}PerfTests/${{ vars.PROJECT_NAME }}PerfTests.csproj"

      - name: Build ${{ vars.PROJECT_NAME }}PerfTests
        run: dotnet build "${{ github.workspace }}/Testing/${{ vars.PROJECT_NAME }}PerfTests/${{ vars.PROJECT_NAME }}PerfTests.csproj" -c Debug --no-restore


  build_samples_project:
    name: Build Samples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Restore Samples Dependencies
        run: dotnet restore "${{ github.workspace }}/Samples/Samples/Samples.csproj"

      - name: Build Samples
        run: dotnet build "${{ github.workspace }}/Samples/Samples/Samples.csproj" -c Debug --no-restore


  build_status_check:
    name: ${{ vars.PROJECT_NAME }} Build Status Check
    needs: [build_main_project, build_perf_project, build_samples_project]
    runs-on: ubuntu-latest
    steps:
      - name: Print Status Check Pass Message
        shell: pwsh
        run: Write-Host "::notice::✅Test Status Check Passed✅";
