name: ✅ Build Status Check
run-name: ✅ Build Status Check (${{ github.base_ref }} branch)


permissions:
  contents: read


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: [main, preview]


jobs:
  build_main_project:
    name: Build ${{ vars.PROJECT_NAME }}
    strategy:
      fail-fast: false
      matrix:
        platform: ["windows-latest", "ubuntu-latest", "macos-latest"]
        build_config: ["Debug", "Release"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 #v5.4.0
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Run Build
        env:
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          BUILD_CONFIG: ${{ matrix.build_config }}
        run: dotnet build "$env:GITHUB_WORKSPACE/$env:PROJECT_NAME/$env:PROJECT_NAME.csproj" -c "$env:BUILD_CONFIG";


  build_perf_project:
    name: Build ${{ vars.PROJECT_NAME }}PerfTests
    strategy:
      fail-fast: false
      matrix:
        platform: ["windows-latest", "ubuntu-latest", "macos-latest"]
        build_config: ["Debug", "Release"]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 #v5.4.0
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Build ${{ vars.PROJECT_NAME }}PerfTests
        env:
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          BUILD_CONFIG: ${{ matrix.build_config }}
        run: dotnet build "$env:GITHUB_WORKSPACE/Testing/$($env:PROJECT_NAME)PerfTests/$($env:PROJECT_NAME)PerfTests.csproj" -c "$env:BUILD_CONFIG";


  build_samples_project:
    name: Build Samples
    strategy:
      fail-fast: false
      matrix:
        platform: ["windows-latest", "ubuntu-latest", "macos-latest"]
        build_config: ["Debug", "Release"]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set Up .NET SDK (${{ vars.NET_SDK_VERSION }})
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 #v5.4.0
        with:
          dotnet-version: ${{ vars.NET_SDK_VERSION }}

      - name: Build Samples
        env:
          BUILD_CONFIG: ${{ matrix.build_config }}
        run: dotnet build "$env:GITHUB_WORKSPACE/Samples/Samples/Samples.csproj" -c "$env:BUILD_CONFIG";


  build_status_check:
    name: ${{ vars.PROJECT_NAME }} Build Status Check
    needs: [build_main_project, build_perf_project, build_samples_project]
    runs-on: ubuntu-latest
    steps:
      - name: Print Status Check Pass Message
        shell: pwsh
        run: Write-Host "::notice::✅Test Status Check Passed✅";
