name: 🔎Main Sonar Scan


defaults:
  run:
    shell: pwsh


on:
  push:
    branches: [preview]


jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Disabling shallow clone is recommended for improving relevancy of reporting
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
