name: ✅Testing Status Check
run-name: ✅Unit Testing Status Check (${{ github.base_ref }} branch)


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: [main, preview]


jobs:
  main_tests:
    name: Run ${{ vars.PROJECT_NAME }} Tests
    uses: KinsonDigital/Infrastructure/.github/workflows/run-csharp-tests.yml@v10.2.1
    with:
      project-name: "${{ vars.PROJECT_NAME }}Tests"
      build-config: Debug
      net-sdk-version: "${{ vars.NET_SDK_VERSION }}"


  integration_tests:
    name: Run ${{ vars.PROJECT_NAME }} Integration Tests
    uses: KinsonDigital/Infrastructure/.github/workflows/run-csharp-tests.yml@v10.2.1
    with:
      project-name: "${{ vars.PROJECT_NAME }}IntegrationTests"
      build-config: Debug
      net-sdk-version: "${{ vars.NET_SDK_VERSION }}"


  test_status_check:
    name: ${{ vars.PROJECT_NAME }} Test Status Check
    needs: [main_tests, integration_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Print Status Check Pass Message
        shell: pwsh
        run: Write-Host "::notice::✅Test Status Check Passed✅";
