name: ✅Testing Status Check
run-name: ✅Testing Status Check ${{ github.base_ref == 'main' && '(Release Build)' || '(Debug Build)' }}


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: [main, preview]


jobs:
  run_unit_tests:
    name: ${{ vars.PROJECT_NAME }} Unit Tests Status Check
    uses: KinsonDigital/Infrastructure/.github/workflows/run-csharp-tests.yml@v9.1.0
    with:
      project-name: "${{ vars.PROJECT_NAME }}Tests"
      build-config: Debug
      net-sdk-version: "${{ vars.NET_SDK_VERSION }}"


  run_integration_tests:
    name: ${{ vars.PROJECT_NAME }} Integration Tests Status Check
    uses: KinsonDigital/Infrastructure/.github/workflows/run-csharp-tests.yml@v9.1.0
    with:
      project-name: "${{ vars.PROJECT_NAME }}IntegrationTests"
      build-config: Debug
      net-sdk-version: "${{ vars.NET_SDK_VERSION }}"
